@hostname = http://localhost:3005

POST {{hostname}}/api/auth/register HTTP/1.1
content-type: application/json

{
  "email": "jenna@doe.com",
  "name": "Jenna Doe",
  "password": "123456"
}

###

POST {{hostname}}/api/auth/signin HTTP/1.1
content-type: application/json

{
  "email": "john@doe.com",
  "password": "123456"
}

###

GET {{hostname}}/api/auth/forgot/jenna@doe.com HTTP/1.1

###

POST {{hostname}}/api/auth/newPassword HTTP/1.1
content-type: application/json

{
  "email": "jenna@doe.com",
  "tempPassword": "qzkda5te",
  "newPassword": "1234"
}

###

POST {{hostname}}/api/auth/singout HTTP/1.1

###

DELETE {{hostname}}/api/auth/ HTTP/1.1
