version: '3.9'

services:
  mysql-db:
    image: mysql:8.1.0
    restart: always
    volumes:
      - database-db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER_NAME}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE_NAME}

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8080:8080"

volumes:
  database-db:
